# -*- coding: utf-8 -*-
# Generated by Django 1.10rc1 on 2016-08-06 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuth', '0002_auto_20160806_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(default='M', max_length=1, null=True),
        ),
    ]
